config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  #see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'pages/about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except:[:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except:[:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum:3,maximum:30}
  validates :description, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3,maximum: 30},
                    uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :username, presence: true, length:{minimum: 3, maximum: 25},
                        uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\Z/i
  validates :email, presence: true, length: {maximum: 105}, 
        uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "you must logged in to perform this action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:show, :edit, :update, :destroy]
  before_action :require_user, except:[:index,:show]
  before_action :require_same_user, only:[:edit,:update]
  def index
    @articles = Article.all 
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show 
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully edited"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was sucessfully deleted"
    redirect_to articles_path
  end
  
  private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title,:description, category_ids: [])
  end
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete own articles"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except:[:show, :index]
  def index
    @categories = Category.all 
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
        flash[:success] = "this category was successfully created"
        redirect_to categories_path
    else
        render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "category name was successfully edited"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.all
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    
    def about

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to articles_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only:[:show, :edit, :update, :destroy]
    before_action :require_same_user, only:[:edit, :update]
    before_action :require_admin, only:[:destroy]
    def index
        @users = User.all
    end
    def new
        @user = User.new 
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to alpha blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end
    
    def show
    end
    
    def edit
    end

    def update
        if @user = User.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to users_path
        else
            render 'edit'
        end
    end
    def destroy
        @user.destroy
        flash[:danger] = "user and all articles created by user have been deleted"
        redirect_to users_path
    end
    private
    def user_params
        params.require(:user).permit(:username,:email,:password)
    end
    def set_user
        @user= User.find(params[:id])
    end
    
    def require_same_user
        if current_user!= @user and !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin can perform this action"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options={size:80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size=options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<p>
<div class="row justify-content-md-center">
    <div class="card bg-light w-75">
        <h4 class="card-header titles"><%= link_to "#{article.title}",
                                article_path(article)%></h4>
        <div class="card-body">
            <%= truncate(article.description,length:100) %>
            <div class="text-muted"><small>
                Created by: <%= article.user.username if article.user%>,
                <%= time_ago_in_words(article.created_at)%> ago,
                Updated at: <%= time_ago_in_words(article.updated_at)%> ago</small>
            </div>
            <% if article.categories.any? %>
                <p>Categories: <%= render article.categories %></p>
            <% end %>
            <% if logged_in? && (current_user == article.user || current_user.admin?)%>
            <div class="article-actions">
                <%= link_to 'Edit', edit_article_path(article),
                class:"btn btn-sm btn-primary" %></td>
                <%= link_to 'Delete', article_path(article),
                method: :delete,data:{confirm:"Are you sure?"},
                class:"btn btn-sm btn-danger"%>
            </div>
            <%end%>
        </div>
    </div>
</div>
</p>
<%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
<%= form_for @article do |f| %>

    <div class="form-group row">
        <div class="col-sm-2 col-form-label">
            <%= f.label :title %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :title, class:"form-control",
            placeholder:"Title of article", autofocus:true %>
        </div>
    </div>
    
    <div class="form-group row">
        <div class="col-sm-2 col-form-label">
            <%= f.label :description %>
        </div>
        <div class="col-sm-8">
            <%= f.text_area :description,rows:10,class:"form-control",
            placeholder:"Body of article" %>
        </div>
    </div>
    
    <div class="form-group row justify-content-md-center">
        <div class="col-sm-8">
            <%=f.collection_check_boxes :category_ids, Category.all, :id,
            :name do |cb|%>
            <%cb.label(class: "checkbox-inline input-checkbox") {cb.check_box(
                class: "checkbox")+ cb.text}%>
            <%end%>
        </div>
    </div>
    
    <div class="form-group row justify-content-md-center">
        <div class="col-sm-8">
            <%=f.submit class:"btn btn-primary btn-lg"%>
        </div>
    </div>
    
    <div class="row justify-content-md-center">
        [ <%= link_to "Cancel request and return to articles listing",
        articles_path %> ]
    </div>

<%end%>

app/views/articles/edit.html.erb
<p><h1 align="center"> Editing article </h1><p>
<%= render 'form' %>

app/views/articles/index.html.erb
<p><h1 align="center"> Listing all articles </h1></p>
<%= render 'article', obj: @articles%>

app/views/articles/new.html.erb
<p><h1 align="center"> Create an article </h1></p>

<%= render 'form'%>

app/views/articles/show.html.erb
<p><h1 align="center"> Showing selected article </h1></p>
<h3 align="center"> Title: <%= @article.title %></h3>

<div class="row justify-content-md-center">
<div class="card bg-light w-75">
    <h4 class=" card-header titles"><strong>Description: </strong></h4>

    <div class="card-body">
        <%= simple_format(@article.description)%>
        <% if @article.categories.any? %>
            <p>Categories: <%= render @article.categories %></p>
        <% end %>
        <div class="article-actions">
        <%if logged_in? && (current_user == @article.user || current_user.admin?)%>
        <%= link_to 'Edit', edit_article_path(@article),
         class:"btn btn-sm btn-primary"%>
        <%= link_to 'Delete', article_path(@article), method: :delete, 
            data:{confirm:"Are you sure you want to delete this article?"},
            class:"btn  btn-sm btn-danger"%>
        <%end%>
        <%= link_to 'view all articles', articles_path, class:"btn btn-sm btn-success"%>
        </div>
    </div>
</div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-info"><%= link_to category.name, 
    category_path(category)%></span>

    

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj:@category%>
<%= form_for @category do |f| %>
    <div class="form-group row">
        <div class="col-sm-2 col-form-label">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class:"form-control",
            placeholder:"Enter category", autofocus:true %>
        </div>
    </div>
    
    <div class="form-group row justify-content-md-center">
        <div class="col-sm-8">
            <%=f.submit class:"btn btn-primary btn-lg"%>
        </div>
    </div>
<%end%>

<div class="row justify-content-md-center">
    [ <%= link_to "Cancel request and return to articles listing",
    articles_path %> ]
</div>

app/views/categories/edit.html.erb
<p><h2 align="center"> Edit category name </h2></p>
<%= render 'form'%>

app/views/categories/index.html.erb
<h1 align="center"> Listing of categories </h1>

<%@categories.each do |category|%>
<p><div class="row justify-content-md-center">
<div class="card text-center" style="width: 19rem;">
    <div class="card-header">
        <div class="card-title">
            <%= link_to "#{category.name}", category_path(category)%>
        </div>
        <small><%= pluralize(category.articles.count,"article")%></small>
    </div>
</div>
</div></p>
<%end%>

app/views/categories/new.html.erb
<h1 align="center"> Create category </h1>
<%= render 'form'%>

app/views/categories/show.html.erb
<h1 align="center"> Articles of category </h1>

<h2 align="center"><span class="badge badge-secondary"><%=@category.name%></span></h2>
<div align="center">
    <% if logged_in? and current_user.admin?%>
    <div class="row">
        <span class="badge"><%= link_to "Edit Category Name", 
        edit_category_path(@category) %></span>
    </div>
    <% end %>
</div>

<%= render 'articles/article', obj: @category_articles %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
    <small>
        Copyright &copy; <a href="#">Komal Devnani</a>
       made with <a href="https://www.udemy.com">Ruby on Rails</a>
        
    </small>
    
    <nav>
    <ul>
        <li><%= link_to "About", pages_about_path %></li>
    </ul>
    </nav>
    </footer>
</div>
<!--©-->

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}"%> alert-dismissible' role='alert'>
        <ul>
            <li><%= msg %></li>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#000000;">
  
  <%= link_to image_tag("logo1.jpg", height:40, width:50) + "Alpha-blog",
   root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" 
  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class:"nav-link"%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
        role="button" data-toggle="dropdown" aria-haspopup="true" 
        aria-expanded="false">
          categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All categories", categories_path, class:"dropdown-item"%>
          <% Category.all.each do |category|%>
            <%= link_to "#{category.name}", category_path(category), class:"dropdown-item"%>
          <%end%>
          <% if logged_in? and current_user.admin?%>
            <div class="dropdown-divider"></div>
            <%= link_to "create new category",new_category_path, class:"dropdown-item"%>
          <%end%>
        </div>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" 
      aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
      Search</button>
    </form>
    
    <ul class="navbar-nav">
    <% if logged_in?%>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
      role="button" data-toggle="dropdown" aria-haspopup="true" 
      aria-expanded="false">
        Your profile<%="Admin" if current_user.admin?%>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "New article", new_article_path, class:"dropdown-item"%>
        <%= link_to "view profile", user_path(current_user), class:"dropdown-item"%>
        <%= link_to "Edit profile", edit_user_path(current_user), 
        class:"dropdown-item"%>
        <div class="dropdown-divider"></div>
        <%= link_to "Log out",logout_path,method: :delete,
          class:"dropdown-item"%>
      </div>
    </li>
    <%else%>
      <li class="nav-item">
        <%= link_to 'sign up', signup_path, class:'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Log in', login_path, class:'nav-link'%>
      </li>
    <%end%></ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> alpha-blog </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development?%>
  </body>
</html>

app/views/pages/about.html.erb
<h1> this is a about page </h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1 class="display-4"> Alpha blog </h1>
    <%= link_to 'Sign up now',signup_path,class:"btn btn-primary btn-lg"%>
</div>

app/views/shared/_errors.html.erb
<%if obj.errors.any? %>
<div class='alert alert-danger' role='alert'>
    <h4 class="alert-heading">
        <%=pluralize(obj.errors.count,"error")%>
        prohibited the article from being saved:
    </h4>
    <p><ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%=msg%></li>
        <%end%>
    </ul></p> 
</div>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user%>
<%= form_for @user do |f| %>

    <div class="form-group row">
        <div class="col-sm-2 col-form-label">
            <%= f.label :username %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :username, class:"form-control",
            placeholder:"Enter username", autofocus:true %>
        </div>
    </div>
    
    <div class="form-group row">
        <div class="col-sm-2 col-form-label">
            <%= f.label :email %>
        </div>
        <div class="col-sm-8">
            <%= f.email_field :email, class:"form-control",
            placeholder:"Enter email" %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-2 col-form-label">
            <%= f.label :password %>
        </div>
        <div class="col-sm-8">
            <%= f.password_field :password,class:"form-control",
            placeholder:"Enter password" %>
        </div>
    </div>
    
    <div class="form-group row justify-content-md-center">
        <div class="col-sm-8">
            <%=f.submit(@user.new_record? ? "Sign Up" : "Update account",
            class:"btn btn-primary btn-lg")%>
        </div>
    </div>
    
    <div class="row justify-content-md-center">
        [ <%= link_to "Cancel request and return to articles listing",
        articles_path %> ]
    </div>
<%end%>

app/views/users/edit.html.erb
<h2 align="center"> Edit your account </h2>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 align="center">Alpha blogger</h1>

<% @users.each do |user| %>
<p>
<div class="row justify-content-md-center">
<div class="col-sm-8">
    <div class="card text-center">
        <%= link_to gravatar_for(user), user_path(user)%>
        <div class="card-body">
            <%= link_to user.username, user_path(user) %>
            <hr>
            <small><%= pluralize(user.articles.count,
            "article") if user.articles %></small>
            <% if logged_in? and current_user.admin?%>
            <%= link_to 'Delete this user', user_path(user),method: :delete, 
            data: {confirm:"Are you sure you want delete your and all their articles?"}%>
            <%end%>
        </div>
    </div>
</div>
</div>
</p>
<%end%>

app/views/users/new.html.erb
<p><h1 align="center">sign up for alpha blog</h1><p>
<%= render 'form'%>

app/views/users/show.html.erb
<p><h2 align="center">Welcome to <%= @user.username%>'s page</h2></p>
<div class="row justify-content-md-center">
    <%= gravatar_for @user,size:100%>
</div>
<h5 align="center">  <%= @user.username%> </h5>
    
<%= render 'articles/article', obj: @user.articles%>